# Generated by Django 4.2.4 on 2023-08-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_visit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Similar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='visit',
            name='date',
            field=models.DateField(verbose_name='Visit Date'),
        ),
        migrations.AddField(
            model_name='building',
            name='similars',
            field=models.ManyToManyField(to='main_app.similar'),
        ),
    ]
