# Generated by Django 4.2.4 on 2023-08-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_similar_alter_visit_options_alter_visit_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Similar',
            new_name='Reference',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='similars',
            new_name='references',
        ),
    ]
